core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persons.urls', namespace='persons')),
    path('account/', include('human.urls')),
    path('social-auth/',
            include('social_django.urls', namespace='social')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

persons/urls.py
from django.urls import path
from . import views

app_name = 'persons'


urlpatterns = [
    path('', views.home, name='home'),
    path('<int:year>/<int:month>/<int:day>/<str:person>/',
         views.person_detail,
         name='person_detail'),
]

persons/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.urls import reverse
from hitcount.models import HitCount



class Person(models.Model):

    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    age = models.PositiveIntegerField(
        help_text="The age of the missing person")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    location = models.CharField(
        max_length=250, help_text="The last known location of the missing person")
    description = models.TextField()
    is_found = models.BooleanField(default=False)
    reported_at = models.DateTimeField(auto_now_add=True)
    reported_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='persons_reported')

    phone_to_call = models.CharField(max_length=250)
    reward =  models.CharField(max_length=250)   

    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')

    class Meta:
        ordering = ['-reported_at']
        indexes = [
            models.Index(fields=['-reported_at']),
        ]

    def __str__(self):
        return self.last_name

    def get_absolute_url(self):
        return reverse('persons:person_detail',
                       args=[self.reported_at.year,
                             self.reported_at.month,
                             self.reported_at.day,
                             self.last_name])


class Comment(models.Model):
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, related_name='comments')

    name = models.CharField(max_length=250)   
    phone = models.CharField(max_length=250)     
    comment = models.TextField()
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.person

persons/views.py
from django.shortcuts import get_object_or_404, redirect, render
from hitcount.utils import get_hitcount_model
from hitcount.views import HitCountMixin

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Comment, Person


def home(request):  

    OBJECT_LIST =  Person.objects.all()
    paginator = Paginator(OBJECT_LIST, 8)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)        
    return render(request, 'person/index.html', {
                                                   'posts' : posts,
                                                   'page' : page,
       })    


def person_detail(request, year, month, day, person):
    person = get_object_or_404(Person,
                             last_name=person,
                             reported_at__year=year,
                             reported_at__month=month,
                             reported_at__day=day)

    latest_comments = Comment.objects.filter(active=True)
    
    # List of active comments for this post
    comments = person.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':

        name  = request.POST['name']
        phone = request.POST['phone']
        comment  = request.POST['comment']

        new_comment = Comment(name=name, phone=phone,comment=comment)
        
        # Assign the current person to the comment
        new_comment.person = person
        
        new_comment.save()                             

    context = {
                'person': person,
                'latest_comments': latest_comments,
                'comments': comments,
                'new_comment': new_comment,           
    }

    # hitcount logic
    hit_count = get_hitcount_model().objects.get_for_object(person)
    hits = hit_count.hits
    hitcontext = context['hitcount'] = {'pk': hit_count.pk}
    hit_count_response = HitCountMixin.hit_count(request, hit_count)
    if hit_count_response.hit_counted:
        hits = hits + 1
        hitcontext['hit_counted'] = hit_count_response.hit_counted
        hitcontext['hit_message'] = hit_count_response.hit_message
        hitcontext['total_hits'] = hits 

    return render(request,
                  'person/person_detail.html', context)    
                  

persons/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Missing Persons</title>
    <script src="https://kit.fontawesome.com/743dee88bd.js" crossorigin="anonymous"></script>
    
    <!-- All Style Links Here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom-animation.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- All Style Links Here End -->


</head>
<body>
    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Missing Persons Board</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'persons:home' %}">Home</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock content %}
     <!-- Footer  -->
    <footer class="footer footer--bg pt-80" data-background="assets/img/bg/footer-bg.jpg" data-overlay="black-oil" data-opacity="85">
        <div class="footer--top">
            <div class="container">
  
                <div class="footer--bottom footer--bottom--border">
                    <div class="row">
                        <div class="col-xl-5 col-lg-6">
                            <div class="footer--copyright">
                                <p>@Copy 2023 <a href="./">Missing Persons Board</a> All Right Reserved.</p>
                            </div>
                        </div>
                        <div class="col-xl-7 col-lg-6 d-none d-md-block">
                            <div class="footer--menu--two">
                                <ul>
                                    <li><a href="{% url 'persons:home' %}">Home</a></li>
         
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer  End -->

    <!-- Fullscreen search -->
    <div class="search-wrap">
        <div class="search-inner">
            <i class="fas fa-times search-close" id="search-close"></i>
            <div class="search-cell">
                <form method="get">
                    <div class="search-field-holder">
                        <input type="search" class="main-search-input" placeholder="Search Your Keyword...">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- end fullscreen search -->

    <!-- Scroll Top Button -->
    <button class="scroll-top tran3s">
        <i class="fa-solid fa-arrow-up-long"></i>
    </button>



<!-- All External JavaScript Links Here -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/tilt.jquery.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.paroller.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- All External JavaScript Links Here End -->

</body>
</html>

persons/templates/pagination.html
<div class="row pt-50">
    <div class="col-sm-12">
        <div class="basic-pagination mb-30">
            <ul>
                {% if page.has_previous %}
                    <li><a href="?page={{ page.previous_page_number }}"><i class="fal fa-angle-left"></i></a></li>
                {% endif %}

                <li class="active"><a href="#">{{ page.number }}</a></li>

                    {% if page.has_next %}
                    <li><a href="?page={{ page.next_page_number }}"><i class="fal fa-angle-right"></i></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>